title: Dakota Wings
description: At Dakota Wings, we are pleased to offer initial or recurrent training in Citation Mustangs or any of the Cessna CJ series aircraft. Our instructors are all current professional pilots and will tailor a course based on your needs and experience.
client:
  name:
  about_markdown: |
    All of Dakota Wings Certified Flight Instructors are currently employed corporate, charter, or military pilots. All are actively flying the aircraft that they are teaching.
  brand: Dakota Wings
  address: 2801 N Jaycee Ln<br>Sioux Falls, SD 57104
  phone: 605-695-5216
  email: rasmussen4@swiftel.net
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  podcast_url:


images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text:
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg

site_colors:
  brand_color: '#185C72'
  theme_color: '#263036'
  accent_color: '#450726'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#443248'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
